version: "3"

services:
  app:
    build: ./
    container_name: amz-tracker
    volumes:
      - ./app:/amz_tracker/app
    restart: unless-stopped
    environment: 
      - PYTHONUNBUFFERED=1
      - "TZ=America/Port_of_Spain"