version: "3"

services:
  tracker-app:
    build: ./
    volumes:
      - ./app:/amz_tracker/app
    restart: unless-stopped
    environment: 
      - PYTHONUNBUFFERED=1
      - "TZ=America/Port_of_Spain"
    depends_on:
      - splash-renderer
    links:
      - splash-renderer 

  splash-renderer:
    image: scrapinghub/splash
    ports:
      - 8050:8050
    restart: unless-stopped
