# Generated by Django 3.2.9 on 2021-11-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_url', models.URLField(max_length=500, verbose_name='Product URL')),
                ('name', models.CharField(max_length=300, verbose_name='Product Name')),
                ('img_url', models.URLField(max_length=500, verbose_name='Product Image URL')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product Price')),
                ('price_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated Price')),
            ],
        ),
        migrations.CreateModel(
            name='UserAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(max_length=200, verbose_name='User Agent')),
            ],
        ),
    ]
